Repository w3c/json-ld-api, pull requests merged in 2025-01, with the labels that each got.

#611 Add compaction to @type map when the compacted item is not already a map.
  tests/compact-manifest.html
  tests/compact-manifest.jsonld
  tests/compact/m023-context.jsonld
  tests/compact/m023-in.jsonld
  tests/compact/m023-out.jsonld
Labels: test:missing-coverage

#608 Resolve the questions about "JSON Serialization" term
  .gitignore
  index.html
Labels: spec:substantive, ErratumRaised, class-3

#623 Fix issue 622
  index.html
Labels: test:needs tests, class-3
